#!/usr/bin/env bash
# Script to install Nginx and configure it to return "Hello World!" on the root path

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[\:\:\]\:80 default_server;/listen \[\:\:\]\:80;/g' /etc/nginx/sites-available/default


sudo service nginx restart
