#!/usr/bin/env bash
# Script to configure Nginx to redirect /redirect_me to another page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a redirection in the Nginx configuration
sudo sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
