#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Update Nginx configuration to use the custom 404 page
sudo sed -i '/server_name _;/a \    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        root /var/www/html;\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
