#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listens on port 8080

sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default

service nginx restart
