#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080 in 7 lines or less
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default
service nginx stop
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /var/www/html
service nginx start
